version: '3'
services:
  php:
    build:
      context: _php
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/
      - ./_php/conf.d:/usr/local/etc/php/conf.d
    env_file:
      - .env

  mysql:
    image: mariadb:10-bionic
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./_mysql/db:/var/lib/mysql:cached
      - ./_mysql/my.cnf:/etc/mysql/my.cnf
    env_file:
      .env

  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - ${NGINX_PORT}:8080
      - ${NGINX_SSL_PORT}:443
    volumes:
      - ./_nginx/conf.d/:/etc/nginx/conf.d/
      - ./_nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./_nginx/ssl:/etc/nginx/ssl
      - ./public:/var/www/html/public
    env_file:
      .env

  node:
    build:
      context: _nodejs
    volumes:
      - ./assets:/usr/src/app/assets
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "npm install"
    env_file:
      .env

  rabbitmq:
    build:
      context: _rabbitmq
    volumes:
      - ./_rabbitmq/data:/data
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15672:15672
    env_file:
      .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
    volumes:
      - /sessions
    ports:
      - ${PMA_PORT}:80